#spring:
#  jpa:
#  hibernate:
#    ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/airways
#    username: root
#    password: rootuser
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    show-sql: true
#
#  kafka:
#    consumer:
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: '*'
#server:
#  port: 9000
#
##  kafka:
##    consumer:
##      bootstrap-servers: localhost:9092
##      group-id: group_id
##      auto-offset-reset: earliest
##      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
##      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
##      #org.apache.kafka.common.serialization.StringSerializer
##    producer:
##      bootstrap-servers: localhost:9092
##      key-serializer: org.apache.kafka.common.serialization.StringSerializer
##      #org.apache.kafka.common.serialization.StringSerializer, org.springframework.kafka.support.serializer.JsonSerializer
##      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
##      #org.apache.kafka.common.serialization.StringSerializer, org.springframework.kafka.support.serializer.JsonSerializer
